
from abc import ABC, abstractmethod

class ICargoRepository(ABC):
    @abstractmethod
    def init(self): ...
    @abstractmethod
    def add(self, cargo): ...
    @abstractmethod
    def list(self, only_active=True): ...

class ITransportRepository(ABC):
    @abstractmethod
    def init(self): ...
    @abstractmethod
    def add(self, transport): ...
    @abstractmethod
    def list(self): ...
